### PR TITLE
Rerender to add maintainers

### PR DESCRIPTION
**Pull request by rafmudaf**
Maintainers were added to the meta.yaml in 560f707062ac73015d8eafcad76722e74de93ac3, but that was pushed directly to the main branch rather than included through a pull request. Therefore, the meta.yaml was not processed by the automated system and the intended action of adding maintainers was not processed. This pull request runs conda-smithy and finalizes adding the maintainers.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
cc @gbarter @deslaughter @andrew-platt

**Comment by rafmudaf** [comment]
@gbarter do you want to be added as well? It might make your life easier while you test the windows build.

**Comment by gbarter** [comment]
Sure thing, thank you!

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
