### PR TITLE
Build OpenFAST for Windows

### PR DESCRIPTION
**Pull request by deslaughter**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This is a pull request for testing in parallel to the RC branch.

### CODE REVIEW

**Comment by deslaughter** [comment]
@conda-forge-admin, please rerender

**Comment by gbarter** [comment]
I think we can cancel this PR.  When I just tested the latest 3.4.1 build package from the `rc` branch-channel on my windows virtual machine, things seemed to be running.  I ran a few of the r-test cases that didn't require compiling a controller.  Might want to test it out on a vanilla windows machine though.

**Comment by rafmudaf** [comment]
I just returned my NREL Windows computer this past week. @andrew-platt @deslaughter do you know anyone who has a Windows computer and is familiar enough with conda to test this? Maybe @ebranlard?

**Comment by rafmudaf** [comment]
That sounds good to me. The test is to install OpenFAST from the `rc` label and run any test case, correct? Is it required to run the full regression test suite?

**Comment by deslaughter** [comment]
I've got Windows on my personal computer so I can try to run the full suite.

**Pull request closed without merging**
